### ISSUE TITLE
System fails to compile an email containing the new question submitted

### ISSUE THREAD

**Issue by addisu292** [umgc/DevSecOpsPlayground#169]
As per the requirement, REQ1.4, the system has failed to compile an email containing the new question submitted to the authorized user. Requirement detail:
REQ1.4: The system shall use the information in the “Ask a question” text field to compile an email and send it via the email bot to authorized users following a user clicking on the “Submit” button. 
Priority: High
Severity: Major

**Comment by acaber** [comment]
This is not an issue. We have changed the requirements to satisfy the need to manage new questions by adding an unanswered question section to the FAQ list page when the user is logged in
